theme: jekyll-theme-time-machine
title: Geometaphors <img src="Geometaphors_1.png" alt="geometaphor logo" width="150"/> 
description: Gender and Language in the Geosciences
avatar: Geometaphors_1.png
