theme: jekyll-theme-serif
title: GeoContext <img src="GeoContext_transparent.png" alt="geocontext logo" width="150"/> 
description: A social and political context for geoscience education
avatar: GeoContext_transparent.png
