theme: jekyll-theme-time-machine
title: Geometaphors <img src="GeoContext_transparent.png" alt="geometaphor logo" width="150"/> 
description: Gender and Language in the Geosciences
avatar: GeoContext_transparent.png
